/* =============================================================================
   TurismoUQ · Proyecto integrador Bases de Datos II · Universidad del Quindío
   Script 01 · DDL: tablas, restricciones, comentarios y vista de apoyo
   Motor: Oracle Database XE 21c
   Ejecución: como el usuario dueño del esquema, en SQL Developer (F5 "Ejecutar
   script") o SQL*Plus. Debe correr de arriba abajo sobre una base limpia; si las
   tablas ya existen, la sección 0 las elimina primero.

   Orden de creación (padres antes que hijas):
     MUNICIPIO, TIPO_ALOJAMIENTO, CIUDAD, ALOJAMIENTO, HABITACION, TEMPORADA,
     CALENDARIO, TARIFA, CLIENTE, USUARIO_SISTEMA, RESERVA, RESERVA_HABITACION,
     SERVICIO, RESERVA_SERVICIO, PAGO, RESENA
   Las 14 entidades del enunciado + 2 agregadas (CIUDAD y CALENDARIO).

   Convenciones de nombres de restricciones:
     pk_<tabla>   llave primaria        fk_<hija>_<padre>  llave foránea
     uq_<tabla>_x única                 ck_<tabla>_x       verificación
   ============================================================================= */

SET SERVEROUTPUT ON
SET DEFINE OFF

/* -----------------------------------------------------------------------------
   0. Limpieza: elimina las tablas si ya existen (ignora ORA-00942 / ORA-00942
      "la tabla no existe") para que el script sea re-ejecutable.
   ----------------------------------------------------------------------------- */
BEGIN
  FOR t IN (SELECT column_value AS nombre
              FROM TABLE(sys.odcivarchar2list(
                     'RESENA','PAGO','RESERVA_SERVICIO','SERVICIO','RESERVA_HABITACION',
                     'RESERVA','USUARIO_SISTEMA','CLIENTE','TARIFA','CALENDARIO',
                     'TEMPORADA','HABITACION','ALOJAMIENTO','CIUDAD',
                     'TIPO_ALOJAMIENTO','MUNICIPIO'))) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.nombre || ' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
    END;
  END LOOP;
  BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW vw_valor_reserva';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
  END;
END;
/

/* =============================================================================
   1. CATÁLOGOS GEOGRÁFICOS Y DE CLASIFICACIÓN
   ============================================================================= */

-- 1.1 MUNICIPIO: los 12 municipios del Quindío (código DANE 63xxx).
CREATE TABLE municipio (
  id_municipio   NUMBER(4)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
  codigo_dane    CHAR(5)        NOT NULL,
  nombre         VARCHAR2(60)   NOT NULL,
  CONSTRAINT pk_municipio        PRIMARY KEY (id_municipio),
  CONSTRAINT uq_municipio_dane   UNIQUE (codigo_dane),
  CONSTRAINT uq_municipio_nombre UNIQUE (nombre),
  CONSTRAINT ck_municipio_dane   CHECK (codigo_dane LIKE '63___')
);
COMMENT ON TABLE  municipio             IS 'Municipios del departamento del Quindío donde se ubican los alojamientos.';
COMMENT ON COLUMN municipio.codigo_dane IS 'Código DANE de 5 dígitos; todos los del Quindío empiezan por 63.';

-- 1.2 TIPO_ALOJAMIENTO: finca cafetera, hotel, glamping, hostal, ecohotel.
CREATE TABLE tipo_alojamiento (
  id_tipo_alojamiento NUMBER(3)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre              VARCHAR2(40)  NOT NULL,
  descripcion         VARCHAR2(300),
  CONSTRAINT pk_tipo_alojamiento        PRIMARY KEY (id_tipo_alojamiento),
  CONSTRAINT uq_tipo_alojamiento_nombre UNIQUE (nombre)
);
COMMENT ON TABLE tipo_alojamiento IS 'Clasificación comercial del alojamiento (finca cafetera, hotel, glamping, hostal, ecohotel).';

-- 1.3 CIUDAD (entidad agregada): ciudad de origen de los clientes.
--     Se separa de MUNICIPIO porque los clientes vienen de todo el país y del
--     exterior; normalizarla evita escribir "Bogota", "Bogotá", "BOGOTA D.C."
--     y permite analizar el origen de los turistas.
CREATE TABLE ciudad (
  id_ciudad      NUMBER(5)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre         VARCHAR2(60)  NOT NULL,
  departamento   VARCHAR2(60),
  pais           VARCHAR2(40)  DEFAULT 'Colombia' NOT NULL,
  CONSTRAINT pk_ciudad            PRIMARY KEY (id_ciudad),
  CONSTRAINT uq_ciudad_nombre_pais UNIQUE (nombre, pais)
);
COMMENT ON TABLE  ciudad              IS 'Ciudades de origen de los clientes (nacionales e internacionales). Entidad agregada al modelo mínimo.';
COMMENT ON COLUMN ciudad.departamento IS 'Departamento, estado o provincia; nulo cuando no aplica.';

/* =============================================================================
   2. OFERTA: ALOJAMIENTOS Y HABITACIONES
   ============================================================================= */

-- 2.1 ALOJAMIENTO
CREATE TABLE alojamiento (
  id_alojamiento      NUMBER(6)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_municipio        NUMBER(4)      NOT NULL,
  id_tipo_alojamiento NUMBER(3)      NOT NULL,
  nombre_comercial    VARCHAR2(100)  NOT NULL,
  direccion           VARCHAR2(150)  NOT NULL,
  estrellas           NUMBER(1)      NOT NULL,
  telefono            VARCHAR2(20)   NOT NULL,
  correo              VARCHAR2(100)  NOT NULL,
  fecha_registro      DATE           NOT NULL,
  activo              CHAR(1)        DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_alojamiento             PRIMARY KEY (id_alojamiento),
  CONSTRAINT fk_alojamiento_municipio   FOREIGN KEY (id_municipio)
                                        REFERENCES municipio (id_municipio),
  CONSTRAINT fk_alojamiento_tipo        FOREIGN KEY (id_tipo_alojamiento)
                                        REFERENCES tipo_alojamiento (id_tipo_alojamiento),
  CONSTRAINT uq_alojamiento_nombre_mun  UNIQUE (nombre_comercial, id_municipio),
  CONSTRAINT uq_alojamiento_correo      UNIQUE (correo),
  CONSTRAINT ck_alojamiento_estrellas   CHECK (estrellas BETWEEN 1 AND 5),
  CONSTRAINT ck_alojamiento_correo      CHECK (correo LIKE '%_@_%._%'),
  CONSTRAINT ck_alojamiento_activo      CHECK (activo IN ('S','N'))
);
COMMENT ON TABLE  alojamiento           IS 'Establecimiento que ofrece habitaciones: pertenece a un municipio y a un tipo.';
COMMENT ON COLUMN alojamiento.estrellas IS 'Calificación de 1 a 5 que el propio alojamiento se autoasigna (no es la de las reseñas).';

-- 2.2 HABITACION
CREATE TABLE habitacion (
  id_habitacion     NUMBER(8)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_alojamiento    NUMBER(6)      NOT NULL,
  numero            VARCHAR2(10)   NOT NULL,
  tipo_habitacion   VARCHAR2(10)   NOT NULL,
  capacidad_maxima  NUMBER(2)      NOT NULL,
  descripcion       VARCHAR2(300),
  activa            CHAR(1)        DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_habitacion             PRIMARY KEY (id_habitacion),
  CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento)
                                       REFERENCES alojamiento (id_alojamiento),
  -- Dos habitaciones del mismo alojamiento no pueden compartir número.
  CONSTRAINT uq_habitacion_numero      UNIQUE (id_alojamiento, numero),
  -- Llave candidata (habitación, alojamiento): la usan las FK compuestas de
  -- RESERVA_HABITACION para garantizar que la habitación sea del alojamiento
  -- de la reserva (ver decisión de diseño 1).
  CONSTRAINT uq_habitacion_aloj        UNIQUE (id_habitacion, id_alojamiento),
  CONSTRAINT ck_habitacion_tipo        CHECK (tipo_habitacion IN ('SENCILLA','DOBLE','SUITE','CABANA')),
  CONSTRAINT ck_habitacion_capacidad   CHECK (capacidad_maxima BETWEEN 1 AND 12),
  CONSTRAINT ck_habitacion_activa      CHECK (activa IN ('S','N'))
);
COMMENT ON TABLE  habitacion                  IS 'Unidad reservable de un alojamiento (habitación, suite, cabaña o domo).';
COMMENT ON COLUMN habitacion.numero           IS 'Identificador visible dentro del alojamiento (101, H3, D02...). Único por alojamiento.';
COMMENT ON COLUMN habitacion.capacidad_maxima IS 'Número máximo de huéspedes que admite.';

/* =============================================================================
   3. PRECIOS: TEMPORADAS, CALENDARIO Y TARIFAS  (decisión de diseño 2)
   ============================================================================= */

-- 3.1 TEMPORADA: un periodo concreto de un año con categoría ALTA/MEDIA/BAJA.
--     "Semana Santa 2025" y "Semana Santa 2026" son filas distintas.
CREATE TABLE temporada (
  id_temporada  NUMBER(5)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nombre        VARCHAR2(80)  NOT NULL,
  categoria     VARCHAR2(5)   NOT NULL,
  anio          NUMBER(4)     NOT NULL,
  fecha_inicio  DATE          NOT NULL,
  fecha_fin     DATE          NOT NULL,
  CONSTRAINT pk_temporada            PRIMARY KEY (id_temporada),
  CONSTRAINT uq_temporada_nombre     UNIQUE (anio, nombre),
  CONSTRAINT uq_temporada_inicio     UNIQUE (fecha_inicio),
  CONSTRAINT ck_temporada_categoria  CHECK (categoria IN ('ALTA','MEDIA','BAJA')),
  CONSTRAINT ck_temporada_rango      CHECK (fecha_fin >= fecha_inicio),
  CONSTRAINT ck_temporada_dias       CHECK (fecha_inicio = TRUNC(fecha_inicio) AND fecha_fin = TRUNC(fecha_fin)),
  -- Las temporadas se definen por año: no pueden cruzar el 31 de diciembre.
  CONSTRAINT ck_temporada_anio       CHECK (EXTRACT(YEAR FROM fecha_inicio) = anio
                                            AND EXTRACT(YEAR FROM fecha_fin) = anio)
);
COMMENT ON TABLE  temporada           IS 'Periodo de un año con una categoría tarifaria (alta, media, baja). Las temporadas de un año cubren todos sus días sin solaparse.';
COMMENT ON COLUMN temporada.categoria IS 'ALTA: Semana Santa, mitad de año, puentes festivos, diciembre-enero. MEDIA y BAJA: el resto.';

-- 3.2 CALENDARIO (entidad agregada): una fila por día, con la temporada vigente.
--     La PK sobre la fecha garantiza que un día pertenece a UNA sola temporada,
--     así que dos temporadas no pueden solaparse. Es la pieza que permite
--     valorar una estadía noche por noche (fn_valor_estadia, Entrega 2) y
--     calcular la ocupación por mes.
CREATE TABLE calendario (
  fecha            DATE        NOT NULL,
  id_temporada     NUMBER(5)   NOT NULL,
  anio             NUMBER(4)   NOT NULL,
  mes              NUMBER(2)   NOT NULL,
  dia_semana       NUMBER(1)   NOT NULL,
  es_fin_de_semana CHAR(1)     NOT NULL,
  CONSTRAINT pk_calendario            PRIMARY KEY (fecha),
  CONSTRAINT fk_calendario_temporada  FOREIGN KEY (id_temporada)
                                      REFERENCES temporada (id_temporada),
  CONSTRAINT ck_calendario_dia        CHECK (fecha = TRUNC(fecha)),
  CONSTRAINT ck_calendario_mes        CHECK (mes BETWEEN 1 AND 12),
  CONSTRAINT ck_calendario_dsem       CHECK (dia_semana BETWEEN 1 AND 7),
  CONSTRAINT ck_calendario_finde      CHECK (es_fin_de_semana IN ('S','N'))
);
COMMENT ON TABLE  calendario            IS 'Dimensión de fechas: un día = una fila = una temporada. Se deriva de los rangos de TEMPORADA. Entidad agregada.';
COMMENT ON COLUMN calendario.dia_semana IS 'Día ISO: 1 = lunes ... 7 = domingo (independiente de la configuración NLS).';

-- 3.3 TARIFA: valor por noche de una habitación en una temporada.
CREATE TABLE tarifa (
  id_tarifa           NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_habitacion       NUMBER(8)      NOT NULL,
  id_temporada        NUMBER(5)      NOT NULL,
  valor_noche         NUMBER(12,2)   NOT NULL,
  fecha_actualizacion DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_tarifa             PRIMARY KEY (id_tarifa),
  CONSTRAINT fk_tarifa_habitacion  FOREIGN KEY (id_habitacion)
                                   REFERENCES habitacion (id_habitacion),
  CONSTRAINT fk_tarifa_temporada   FOREIGN KEY (id_temporada)
                                   REFERENCES temporada (id_temporada),
  -- Una sola tarifa por cada combinación habitación × temporada.
  CONSTRAINT uq_tarifa_hab_temp    UNIQUE (id_habitacion, id_temporada),
  CONSTRAINT ck_tarifa_valor       CHECK (valor_noche > 0)
);
COMMENT ON TABLE  tarifa             IS 'Precio por noche de cada habitación en cada temporada. No es un porcentaje sobre un precio base: cada alojamiento fija su valor.';
COMMENT ON COLUMN tarifa.valor_noche IS 'Pesos colombianos (COP) por noche.';

/* =============================================================================
   4. PERSONAS: CLIENTES Y USUARIOS INTERNOS
   ============================================================================= */

-- 4.1 CLIENTE
CREATE TABLE cliente (
  id_cliente        NUMBER(8)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
  tipo_documento    VARCHAR2(3)    NOT NULL,
  numero_documento  VARCHAR2(20)   NOT NULL,
  nombres           VARCHAR2(60)   NOT NULL,
  apellidos         VARCHAR2(60)   NOT NULL,
  correo            VARCHAR2(120)  NOT NULL,
  telefono          VARCHAR2(20)   NOT NULL,
  id_ciudad_origen  NUMBER(5)      NOT NULL,
  fecha_registro    DATE           NOT NULL,
  CONSTRAINT pk_cliente            PRIMARY KEY (id_cliente),
  CONSTRAINT fk_cliente_ciudad     FOREIGN KEY (id_ciudad_origen)
                                   REFERENCES ciudad (id_ciudad),
  CONSTRAINT uq_cliente_documento  UNIQUE (tipo_documento, numero_documento),
  CONSTRAINT uq_cliente_correo     UNIQUE (correo),
  CONSTRAINT ck_cliente_tipo_doc   CHECK (tipo_documento IN ('CC','CE','PAS')),
  CONSTRAINT ck_cliente_correo     CHECK (correo LIKE '%_@_%._%')
);
COMMENT ON TABLE  cliente                IS 'Persona que hace reservas. Un cliente puede tener muchas reservas en el tiempo.';
COMMENT ON COLUMN cliente.tipo_documento IS 'CC cédula de ciudadanía, CE cédula de extranjería, PAS pasaporte.';

-- 4.2 USUARIO_SISTEMA: usuarios internos de la plataforma.
--     Los encargados y recepcionistas pertenecen a UN alojamiento; los roles de
--     plataforma (administrador, gerente, auditor) no tienen alojamiento.
--     Esto es la base de la seguridad por filas de la Entrega 3.
CREATE TABLE usuario_sistema (
  id_usuario      NUMBER(5)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username        VARCHAR2(30)   NOT NULL,
  nombre_completo VARCHAR2(100)  NOT NULL,
  correo          VARCHAR2(120)  NOT NULL,
  rol             VARCHAR2(20)   NOT NULL,
  id_alojamiento  NUMBER(6),
  activo          CHAR(1)        DEFAULT 'S' NOT NULL,
  fecha_creacion  DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_usuario_sistema      PRIMARY KEY (id_usuario),
  CONSTRAINT fk_usuario_alojamiento  FOREIGN KEY (id_alojamiento)
                                     REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uq_usuario_username     UNIQUE (username),
  CONSTRAINT uq_usuario_correo       UNIQUE (correo),
  CONSTRAINT ck_usuario_username     CHECK (username = UPPER(username)),
  CONSTRAINT ck_usuario_rol          CHECK (rol IN ('ADMIN_PLATAFORMA','GERENTE','AUDITOR',
                                                    'ADMIN_ALOJAMIENTO','RECEPCION')),
  -- Rol de alojamiento <=> tiene alojamiento asignado.
  CONSTRAINT ck_usuario_rol_aloj     CHECK (
       (rol IN ('ADMIN_ALOJAMIENTO','RECEPCION')          AND id_alojamiento IS NOT NULL)
    OR (rol IN ('ADMIN_PLATAFORMA','GERENTE','AUDITOR')   AND id_alojamiento IS NULL)),
  CONSTRAINT ck_usuario_activo       CHECK (activo IN ('S','N'))
);
COMMENT ON TABLE  usuario_sistema          IS 'Usuarios internos de TurismoUQ con su rol. Los de alojamiento solo gestionan su propio alojamiento.';
COMMENT ON COLUMN usuario_sistema.username IS 'Debe coincidir con el usuario de Oracle (en mayúsculas) para filtrar por SYS_CONTEXT(''USERENV'',''SESSION_USER'').';

/* =============================================================================
   5. RESERVAS  (decisión de diseño 1)
   ============================================================================= */

-- 5.1 RESERVA: encabezado. Una reserva pertenece a un cliente y a UN alojamiento.
CREATE TABLE reserva (
  id_reserva        NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_cliente        NUMBER(8)      NOT NULL,
  id_alojamiento    NUMBER(6)      NOT NULL,
  fecha_reserva     DATE           NOT NULL,
  fecha_checkin     DATE           NOT NULL,
  fecha_checkout    DATE           NOT NULL,
  estado            VARCHAR2(12)   DEFAULT 'PENDIENTE' NOT NULL,
  fecha_cancelacion DATE,
  observaciones     VARCHAR2(300),
  CONSTRAINT pk_reserva              PRIMARY KEY (id_reserva),
  CONSTRAINT fk_reserva_cliente      FOREIGN KEY (id_cliente)
                                     REFERENCES cliente (id_cliente),
  CONSTRAINT fk_reserva_alojamiento  FOREIGN KEY (id_alojamiento)
                                     REFERENCES alojamiento (id_alojamiento),
  -- Llave candidata usada por las FK compuestas de las líneas.
  CONSTRAINT uq_reserva_aloj         UNIQUE (id_reserva, id_alojamiento),
  CONSTRAINT ck_reserva_estado       CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA')),
  CONSTRAINT ck_reserva_dias         CHECK (fecha_checkin = TRUNC(fecha_checkin)
                                            AND fecha_checkout = TRUNC(fecha_checkout)),
  CONSTRAINT ck_reserva_fechas       CHECK (fecha_checkout > fecha_checkin),
  CONSTRAINT ck_reserva_max_noches   CHECK (fecha_checkout - fecha_checkin <= 30),
  CONSTRAINT ck_reserva_anticipada   CHECK (TRUNC(fecha_reserva) <= fecha_checkin),
  -- Solo las canceladas tienen fecha de cancelación, y es posterior a la reserva.
  CONSTRAINT ck_reserva_cancelacion  CHECK (
       (estado = 'CANCELADA'  AND fecha_cancelacion IS NOT NULL
                              AND fecha_cancelacion >= TRUNC(fecha_reserva))
    OR (estado <> 'CANCELADA' AND fecha_cancelacion IS NULL))
);
COMMENT ON TABLE  reserva                   IS 'Encabezado de la reserva: cliente, alojamiento, rango general de fechas y estado. El detalle de habitaciones está en RESERVA_HABITACION.';
COMMENT ON COLUMN reserva.fecha_checkin     IS 'Inicio del rango general: la menor fecha de llegada de sus líneas.';
COMMENT ON COLUMN reserva.fecha_checkout    IS 'Fin del rango general: la mayor fecha de salida de sus líneas.';
COMMENT ON COLUMN reserva.fecha_cancelacion IS 'Define el derecho a reembolso: más de 5 días antes del check-in => 80 %.';

-- 5.2 RESERVA_HABITACION: línea de reserva (una por habitación reservada).
CREATE TABLE reserva_habitacion (
  id_reserva_habitacion NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva            NUMBER(10)    NOT NULL,
  id_alojamiento        NUMBER(6)     NOT NULL,
  id_habitacion         NUMBER(8)     NOT NULL,
  fecha_checkin         DATE          NOT NULL,
  fecha_checkout        DATE          NOT NULL,
  num_huespedes         NUMBER(2)     NOT NULL,
  valor_estadia         NUMBER(14,2)  NOT NULL,
  CONSTRAINT pk_reserva_habitacion  PRIMARY KEY (id_reserva_habitacion),
  -- FK compuesta: la línea pertenece a una reserva DE ESE alojamiento...
  CONSTRAINT fk_rh_reserva          FOREIGN KEY (id_reserva, id_alojamiento)
                                    REFERENCES reserva (id_reserva, id_alojamiento)
                                    ON DELETE CASCADE,
  -- ...y la habitación es DE ESE MISMO alojamiento.
  CONSTRAINT fk_rh_habitacion       FOREIGN KEY (id_habitacion, id_alojamiento)
                                    REFERENCES habitacion (id_habitacion, id_alojamiento),
  CONSTRAINT uq_rh_reserva_hab      UNIQUE (id_reserva, id_habitacion),
  CONSTRAINT ck_rh_dias             CHECK (fecha_checkin = TRUNC(fecha_checkin)
                                           AND fecha_checkout = TRUNC(fecha_checkout)),
  CONSTRAINT ck_rh_fechas           CHECK (fecha_checkout > fecha_checkin),
  CONSTRAINT ck_rh_huespedes        CHECK (num_huespedes > 0),
  CONSTRAINT ck_rh_valor            CHECK (valor_estadia >= 0)
);
COMMENT ON TABLE  reserva_habitacion               IS 'Detalle de la reserva: cada habitación con sus propias fechas (pueden diferir dentro del rango general).';
COMMENT ON COLUMN reserva_habitacion.id_alojamiento IS 'Redundancia controlada: participa en las dos FK compuestas que obligan a que todas las habitaciones sean del alojamiento de la reserva.';
COMMENT ON COLUMN reserva_habitacion.valor_estadia  IS 'Suma noche a noche de la tarifa vigente cada día, congelada al reservar (si la tarifa cambia después, la reserva no cambia).';

/* =============================================================================
   6. SERVICIOS COMPLEMENTARIOS
   ============================================================================= */

-- 6.1 SERVICIO: cada servicio pertenece a un alojamiento específico.
CREATE TABLE servicio (
  id_servicio     NUMBER(6)      GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_alojamiento  NUMBER(6)      NOT NULL,
  nombre          VARCHAR2(60)   NOT NULL,
  descripcion     VARCHAR2(300),
  precio          NUMBER(12,2)   NOT NULL,
  activo          CHAR(1)        DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_servicio             PRIMARY KEY (id_servicio),
  CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento)
                                     REFERENCES alojamiento (id_alojamiento),
  -- El "Desayuno" del Hotel X y el del Hotel Y son servicios distintos,
  -- pero un alojamiento no repite el nombre de un servicio.
  CONSTRAINT uq_servicio_nombre      UNIQUE (id_alojamiento, nombre),
  CONSTRAINT uq_servicio_aloj        UNIQUE (id_servicio, id_alojamiento),
  CONSTRAINT ck_servicio_precio      CHECK (precio > 0),
  CONSTRAINT ck_servicio_activo      CHECK (activo IN ('S','N'))
);
COMMENT ON TABLE servicio IS 'Servicio adicional (desayuno, tour, transporte...) ofrecido por un alojamiento concreto, con su precio.';

-- 6.2 RESERVA_SERVICIO: servicios contratados en una reserva, con cantidad.
CREATE TABLE reserva_servicio (
  id_reserva_servicio NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva          NUMBER(10)    NOT NULL,
  id_alojamiento      NUMBER(6)     NOT NULL,
  id_servicio         NUMBER(6)     NOT NULL,
  cantidad            NUMBER(3)     NOT NULL,
  precio_unitario     NUMBER(12,2)  NOT NULL,
  subtotal            NUMBER(14,2)  GENERATED ALWAYS AS (cantidad * precio_unitario) VIRTUAL,
  CONSTRAINT pk_reserva_servicio  PRIMARY KEY (id_reserva_servicio),
  -- Mismo patrón de FK compuestas: solo se pueden contratar servicios del
  -- alojamiento de la reserva.
  CONSTRAINT fk_rs_reserva        FOREIGN KEY (id_reserva, id_alojamiento)
                                  REFERENCES reserva (id_reserva, id_alojamiento)
                                  ON DELETE CASCADE,
  CONSTRAINT fk_rs_servicio       FOREIGN KEY (id_servicio, id_alojamiento)
                                  REFERENCES servicio (id_servicio, id_alojamiento),
  CONSTRAINT uq_rs_reserva_serv   UNIQUE (id_reserva, id_servicio),
  CONSTRAINT ck_rs_cantidad       CHECK (cantidad > 0),
  CONSTRAINT ck_rs_precio         CHECK (precio_unitario > 0)
);
COMMENT ON TABLE  reserva_servicio                 IS 'Servicios contratados dentro de una reserva; la cantidad permite pedir varias unidades.';
COMMENT ON COLUMN reserva_servicio.precio_unitario IS 'Precio del servicio en el momento de contratarlo (copia congelada de SERVICIO.PRECIO).';
COMMENT ON COLUMN reserva_servicio.subtotal        IS 'Columna virtual = cantidad * precio_unitario.';

/* =============================================================================
   7. PAGOS
   ============================================================================= */
CREATE TABLE pago (
  id_pago           NUMBER(10)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva        NUMBER(10)    NOT NULL,
  fecha_pago        DATE          NOT NULL,
  concepto          VARCHAR2(10)  NOT NULL,
  monto             NUMBER(14,2)  NOT NULL,
  metodo            VARCHAR2(16)  NOT NULL,
  estado            VARCHAR2(12)  NOT NULL,
  monto_reembolsado NUMBER(14,2),
  fecha_reembolso   DATE,
  CONSTRAINT pk_pago            PRIMARY KEY (id_pago),
  CONSTRAINT fk_pago_reserva    FOREIGN KEY (id_reserva)
                                REFERENCES reserva (id_reserva),
  CONSTRAINT ck_pago_monto      CHECK (monto > 0),
  CONSTRAINT ck_pago_concepto   CHECK (concepto IN ('ANTICIPO','SALDO','TOTAL')),
  CONSTRAINT ck_pago_metodo     CHECK (metodo IN ('TARJETA_CREDITO','TARJETA_DEBITO','PSE',
                                                  'TRANSFERENCIA','EFECTIVO')),
  CONSTRAINT ck_pago_estado     CHECK (estado IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')),
  -- Un reembolso nunca supera lo pagado y solo existe en pagos REEMBOLSADOS.
  CONSTRAINT ck_pago_reembolso  CHECK (
       (estado = 'REEMBOLSADO'  AND monto_reembolsado IS NOT NULL
                                AND monto_reembolsado > 0
                                AND monto_reembolsado <= monto
                                AND fecha_reembolso IS NOT NULL
                                AND fecha_reembolso >= TRUNC(fecha_pago))
    OR (estado <> 'REEMBOLSADO' AND monto_reembolsado IS NULL
                                AND fecha_reembolso IS NULL))
);
COMMENT ON TABLE  pago                   IS 'Abonos de una reserva (anticipo, saldo o pago total). La reserva está pagada cuando sus pagos EXITOSOS cubren estadía + servicios.';
COMMENT ON COLUMN pago.estado            IS 'REEMBOLSADO: el pago fue exitoso y luego se devolvió monto_reembolsado (80 % si se canceló con más de 5 días).';
COMMENT ON COLUMN pago.monto_reembolsado IS 'Valor devuelto al cliente; monto - monto_reembolsado es lo que retiene el alojamiento.';

/* =============================================================================
   8. RESEÑAS
   ============================================================================= */
CREATE TABLE resena (
  id_resena     NUMBER(10)     GENERATED BY DEFAULT ON NULL AS IDENTITY,
  id_reserva    NUMBER(10)     NOT NULL,
  calificacion  NUMBER(1)      NOT NULL,
  comentario    VARCHAR2(500),
  fecha_resena  DATE           NOT NULL,
  CONSTRAINT pk_resena               PRIMARY KEY (id_resena),
  -- La reseña nace de una reserva: así se sabe qué cliente opina sobre qué
  -- alojamiento y se garantiza que estuvo allí. Una reseña por reserva.
  CONSTRAINT fk_resena_reserva       FOREIGN KEY (id_reserva)
                                     REFERENCES reserva (id_reserva),
  CONSTRAINT uq_resena_reserva       UNIQUE (id_reserva),
  CONSTRAINT ck_resena_calificacion  CHECK (calificacion BETWEEN 1 AND 5)
);
COMMENT ON TABLE  resena            IS 'Opinión del cliente sobre el alojamiento tras una reserva COMPLETADA (validación de estado: disparador en Entrega 2).';
COMMENT ON COLUMN resena.comentario IS 'Opcional.';

/* =============================================================================
   9. VISTA DE APOYO: valor total y estado de pago de cada reserva
      total = estadía (todas las habitaciones) + servicios
      pagada = SUM(pagos EXITOSOS) >= total
   ============================================================================= */
CREATE OR REPLACE VIEW vw_valor_reserva AS
SELECT r.id_reserva,
       r.id_alojamiento,
       r.estado,
       NVL(h.valor_estadia, 0)                          AS valor_estadia,
       NVL(s.valor_servicios, 0)                        AS valor_servicios,
       NVL(h.valor_estadia, 0) + NVL(s.valor_servicios, 0) AS valor_total,
       NVL(p.pagado_exitoso, 0)                         AS pagado_exitoso,
       NVL(p.retenido_cancelacion, 0)                   AS retenido_cancelacion,
       CASE WHEN NVL(p.pagado_exitoso, 0) >= NVL(h.valor_estadia, 0) + NVL(s.valor_servicios, 0)
            THEN 'S' ELSE 'N' END                       AS pagada
  FROM reserva r
  LEFT JOIN (SELECT id_reserva, SUM(valor_estadia) AS valor_estadia
               FROM reserva_habitacion GROUP BY id_reserva) h
         ON h.id_reserva = r.id_reserva
  LEFT JOIN (SELECT id_reserva, SUM(subtotal) AS valor_servicios
               FROM reserva_servicio GROUP BY id_reserva) s
         ON s.id_reserva = r.id_reserva
  LEFT JOIN (SELECT id_reserva,
                    SUM(CASE WHEN estado = 'EXITOSO' THEN monto END)                      AS pagado_exitoso,
                    SUM(CASE WHEN estado = 'REEMBOLSADO' THEN monto - monto_reembolsado END) AS retenido_cancelacion
               FROM pago GROUP BY id_reserva) p
         ON p.id_reserva = r.id_reserva;

COMMENT ON TABLE vw_valor_reserva IS 'Valor de estadía, servicios, total y si la reserva está pagada (pagos EXITOSOS >= total).';

PROMPT === 01_ddl.sql terminado: 16 tablas y 1 vista creadas ===
